-- lvim.builtin.gitsigns.opts.signs.add.text = '+'
-- lvim.builtin.gitsigns.opts.signs.delete.text = '-'
-- lvim.builtin.gitsigns.opts.signs.change.text = 'c'
-- lvim.builtin.gitsigns.opts.signs.changedelete.text = 'c-'
